# Link Tennis Data Uk <-> Sackmann

In [2]:
import os
from pathlib import Path
import pandas as pd
from dotenv import load_dotenv, find_dotenv

from tennis_data_pipeline.loader.uk import load_clean_uk_atp_data
from tennis_data_pipeline.datasources import sackmann as sk

PROJECT_DIR = Path(find_dotenv(".env.template")).parent
print(PROJECT_DIR)

/Users/nicholasbenelli/Workspace/repos/GitHub/-sports/-tennis/Tennis-Data-Pipeline

In [3]:
YEAR = 2025
TOUR = "atp"

if TOUR.lower() == "atp":
    sk_tour = sk.atp
elif TOUR.lower() == "wta":
    sk_tour = sk.wta
else:
    raise ValueError(f"Unsupported tour: {TOUR}")

In [4]:
df_uk = load_clean_uk_atp_data(
    PROJECT_DIR / f"data/clean/uk/{TOUR.lower()}/uk_{TOUR.lower()}_singles_clean_{YEAR}.csv"
)

print("Tennis-Data Uk")
print(list(df_uk.columns))
display(df_uk)


df_sackmann = sk_tour.load_year(YEAR)

print("Sackmann")
print(list(df_sackmann.columns))
display(df_sackmann)

Tennis-Data Uk
['source', 'tour', 'year', 'uk_tournament_id', 'tournament_name', 'location', 'match_date', 'series', 'is_outdoor', 'surface', 'round', 'players_remaining', 'best_of', 'winner_name', 'loser_name', 'winner_rank', 'loser_rank', 'winner_rank_points', 'loser_rank_points', 'winner_sets', 'loser_sets', 'winner_set_1_games', 'loser_set_1_games', 'winner_set_2_games', 'loser_set_2_games', 'winner_set_3_games', 'loser_set_3_games', 'winner_set_4_games', 'loser_set_4_games', 'winner_set_5_games', 'loser_set_5_games', 'match_status', 'odds_b365_winner', 'odds_b365_loser', 'odds_pinnacle_winner', 'odds_pinnacle_loser', 'odds_max_winner', 'odds_max_loser', 'odds_avg_winner', 'odds_avg_loser', 'source_event_key', 'source_match_key']

,source,tour,year,uk_tournament_id,tournament_name,location,match_date,series,is_outdoor,surface,...,odds_b365_winner,odds_b365_loser,odds_pinnacle_winner,odds_pinnacle_loser,odds_max_winner,odds_max_loser,odds_avg_winner,odds_avg_loser,source_event_key,source_match_key
0,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-29,atp_250,True,hard,...,2.00,1.80,2.08,1.83,2.14,1.83,2.03,1.78,2025_1_brisbane_brisbane_international,2025_1_brisbane_brisbane_international_2024-12...
1,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,1.44,2.75,1.48,2.85,1.48,2.90,1.43,2.74,2025_1_brisbane_brisbane_international,2025_1_brisbane_brisbane_international_2024-12...
2,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,1.67,2.20,1.73,2.22,1.73,2.25,1.67,2.18,2025_1_brisbane_brisbane_international,2025_1_brisbane_brisbane_international_2024-12...
3,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,1.53,2.50,1.64,2.39,1.65,2.50,1.59,2.36,2025_1_brisbane_brisbane_international,2025_1_brisbane_brisbane_international_2024-12...
4,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,2.63,1.50,2.47,1.60,2.63,1.60,2.48,1.54,2025_1_brisbane_brisbane_international,2025_1_brisbane_brisbane_international_2024-12...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2639,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-14,tour_finals,False,hard,...,1.05,10.00,1.10,8.53,1.07,11.00,1.06,9.41,2025_60_turin_masters_cup,2025_60_turin_masters_cup_2025-11-14_RR_sinner...
2640,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-14,tour_finals,False,hard,...,1.20,4.50,1.21,5.06,1.22,5.30,1.19,4.80,2025_60_turin_masters_cup,2025_60_turin_masters_cup_2025-11-14_RR_auger_...
2641,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-15,tour_finals,False,hard,...,1.05,10.00,1.10,8.53,1.07,11.00,1.06,9.44,2025_60_turin_masters_cup,2025_60_turin_masters_cup_2025-11-15_SF_sinner...
2642,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-15,tour_finals,False,hard,...,1.20,4.50,1.21,5.06,1.22,5.30,1.19,4.75,2025_60_turin_masters_cup,2025_60_turin_masters_cup_2025-11-15_SF_alcara...
2643,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-16,tour_finals,False,hard,...,1.50,2.63,1.50,2.80,1.56,2.80,1.49,2.61,2025_60_turin_masters_cup,2025_60_turin_masters_cup_2025-11-16_F_sinner_...

Sackmann
['tourney_id', 'tourney_name', 'surface', 'draw_size', 'tourney_level', 'tourney_date', 'match_num', 'winner_id', 'winner_seed', 'winner_entry', 'winner_name', 'winner_hand', 'winner_ht', 'winner_ioc', 'winner_age', 'loser_id', 'loser_seed', 'loser_entry', 'loser_name', 'loser_hand', 'loser_ht', 'loser_ioc', 'loser_age', 'score', 'best_of', 'round', 'minutes', 'w_ace', 'w_df', 'w_svpt', 'w_1stIn', 'w_1stWon', 'w_2ndWon', 'w_SvGms', 'w_bpSaved', 'w_bpFaced', 'l_ace', 'l_df', 'l_svpt', 'l_1stIn', 'l_1stWon', 'l_2ndWon', 'l_SvGms', 'l_bpSaved', 'l_bpFaced', 'winner_rank', 'winner_rank_points', 'loser_rank', 'loser_rank_points', 'source_year', 'tour', 'match_type', 'match_level']

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,source_year,tour,match_type,match_level
0,2025-9900,United Cup,Hard,18,A,2024-12-27,400,126203,<NA>,NaN,...,1,2,4,5100,16,2640,2025,atp,singles,main
1,2025-9900,United Cup,Hard,18,A,2024-12-27,399,126203,<NA>,NaN,...,1,4,4,5100,25,1758,2025,atp,singles,main
2,2025-9900,United Cup,Hard,18,A,2024-12-27,398,128034,<NA>,NaN,...,1,4,16,2640,78,715,2025,atp,singles,main
3,2025-9900,United Cup,Hard,18,A,2024-12-27,397,126203,<NA>,NaN,...,7,9,4,5100,45,1155,2025,atp,singles,main
4,2025-9900,United Cup,Hard,18,A,2024-12-27,396,207830,<NA>,NaN,...,0,4,25,1758,32,1472,2025,atp,singles,main
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2939,2025-M-DC-2025-WG2-PO-SLO-INA-01,Davis Cup WG2 PO: SLO vs INA,Clay,4,D,2025-02-01,2,210107,<NA>,NaN,...,<NA>,<NA>,447,94,<NA>,<NA>,2025,atp,singles,main
2940,2025-M-DC-2025-WG2-PO-SLO-INA-01,Davis Cup WG2 PO: SLO vs INA,Clay,4,D,2025-02-01,4,210107,<NA>,NaN,...,<NA>,<NA>,447,94,<NA>,<NA>,2025,atp,singles,main
2941,2025-M-DC-2025-WG2-PO-ZIM-MAR-01,Davis Cup WG2 PO: ZIM vs MAR,Hard,4,D,2025-01-31,1,207220,<NA>,NaN,...,<NA>,<NA>,749,33,2068,1,2025,atp,singles,main
2942,2025-M-DC-2025-WG2-PO-ZIM-MAR-01,Davis Cup WG2 PO: ZIM vs MAR,Hard,4,D,2025-01-31,2,200611,<NA>,NaN,...,<NA>,<NA>,608,54,<NA>,<NA>,2025,atp,singles,main
2943,2025-M-DC-2025-WG2-PO-ZIM-MAR-01,Davis Cup WG2 PO: ZIM vs MAR,Hard,4,D,2025-01-31,4,211558,<NA>,NaN,...,<NA>,<NA>,1170,8,<NA>,<NA>,2025,atp,singles,main

In [6]:
from tennis_data_pipeline.loader.mapper import load_tournament_source_links

df_tournament = load_tournament_source_links(TOUR, PROJECT_DIR / "data/mapping")
df_tournament = df_tournament.loc[df_tournament.year == YEAR]

print("Tournaments")
print(list(df_tournament.columns))
display(df_tournament)

Tournaments
['official_tournament_id', 'year', 'source', 'source_tournament_id']

,official_tournament_id,year,source,source_tournament_id
1653,301,2025,sackmann,2025-0301
1654,308,2025,sackmann,2025-0308
1655,311,2025,sackmann,2025-0311
1656,314,2025,sackmann,2025-0314
1657,316,2025,sackmann,2025-0316
...,...,...,...,...
3386,605,2025,tennis_data_uk,2025_60_turin_masters_cup
3387,375,2025,tennis_data_uk,2025_6_montpellier_open_sud_de_france
3388,424,2025,tennis_data_uk,2025_7_dallas_dallas_open
3389,407,2025,tennis_data_uk,2025_8_rotterdam_abn_amro_world_tennis_tournament
3390,506,2025,tennis_data_uk,2025_9_buenos_aires_argentina_open

In [7]:
N_SAMPLES = 10

df_uk_sample = df_uk.sample(n=N_SAMPLES, random_state=42)
df_sackmann_sample = df_sackmann.sample(n=N_SAMPLES, random_state=42)
df_tournament_sample = df_tournament.sample(n=N_SAMPLES, random_state=42)

print("UK sample")
display(df_uk_sample)

print("Sackmann sample")
display(df_sackmann_sample)

print("Tournament sample")
display(df_tournament_sample)

UK sample

,source,tour,year,uk_tournament_id,tournament_name,location,match_date,series,is_outdoor,surface,...,odds_b365_winner,odds_b365_loser,odds_pinnacle_winner,odds_pinnacle_loser,odds_max_winner,odds_max_loser,odds_avg_winner,odds_avg_loser,source_event_key,source_match_key
889,tennis_data_uk,atp,2025,23,Barcelona Open,Barcelona,2025-04-14,atp_500,True,clay,...,1.44,2.75,1.46,2.91,1.52,2.95,1.45,2.75,2025_23_barcelona_barcelona_open,2025_23_barcelona_barcelona_open_2025-04-14_R3...
1110,tennis_data_uk,atp,2025,26,Internazionali BNL d'Italia,Rome,2025-05-11,masters_1000,True,clay,...,1.17,5.00,1.18,5.43,1.20,5.80,1.17,5.15,2025_26_rome_internazionali_bnl_d_italia,2025_26_rome_internazionali_bnl_d_italia_2025-...
1309,tennis_data_uk,atp,2025,29,French Open,Paris,2025-06-01,grand_slam,True,clay,...,1.05,11.00,1.05,13.88,1.07,14.00,1.04,11.11,2025_29_paris_french_open,2025_29_paris_french_open_2025-06-01_R16_alcar...
727,tennis_data_uk,atp,2025,18,Miami Open,Miami,2025-03-24,masters_1000,True,hard,...,1.50,2.63,1.53,2.69,1.58,2.69,1.51,2.54,2025_18_miami_miami_open,2025_18_miami_miami_open_2025-03-24_R32_machac...
1027,tennis_data_uk,atp,2025,25,Mutua Madrid Open,Madrid,2025-04-29,masters_1000,True,clay,...,2.00,1.80,2.06,1.85,2.10,1.89,2.01,1.82,2025_25_madrid_mutua_madrid_open,2025_25_madrid_mutua_madrid_open_2025-04-29_R3...
1472,tennis_data_uk,atp,2025,35,Mallorca Championships,Mallorca,2025-06-23,atp_250,True,grass,...,1.62,2.30,1.63,2.41,1.68,2.42,1.61,2.29,2025_35_mallorca_mallorca_championships,2025_35_mallorca_mallorca_championships_2025-0...
748,tennis_data_uk,atp,2025,18,Miami Open,Miami,2025-03-28,masters_1000,True,hard,...,3.40,1.33,3.40,1.37,3.40,1.37,3.27,1.34,2025_18_miami_miami_open,2025_18_miami_miami_open_2025-03-28_SF_mensik_...
1264,tennis_data_uk,atp,2025,29,French Open,Paris,2025-05-28,grand_slam,True,clay,...,2.38,1.57,2.37,1.66,2.50,1.66,2.41,1.58,2025_29_paris_french_open,2025_29_paris_french_open_2025-05-28_R64_halys...
2617,tennis_data_uk,atp,2025,59,Open de Moselle,Metz,2025-11-05,atp_250,False,hard,...,2.75,1.44,2.77,1.50,2.88,1.45,2.73,1.44,2025_59_metz_open_de_moselle,2025_59_metz_open_de_moselle_2025-11-05_R16_ta...
1612,tennis_data_uk,atp,2025,36,Wimbledon,London,2025-07-07,grand_slam,True,grass,...,1.03,13.00,1.03,18.06,1.05,18.06,1.03,13.83,2025_36_london_wimbledon,2025_36_london_wimbledon_2025-07-07_R16_sinner...

Sackmann sample

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,source_year,tour,match_type,match_level
565,2025-8996,Santiago,Clay,28,A,2025-02-24,377,144869,5,NaN,...,4,8,43,1240,147,402,2025,atp,singles,main
1220,2025-520,Roland Garros,Clay,128,G,2025-05-26,401,207989,2,NaN,...,7,14,2,8850,1,10380,2025,atp,singles,main
1677,2025-0314,Gstaad,Clay,28,A,2025-07-14,379,122330,2,NaN,...,2,4,34,1585,74,824,2025,atp,singles,main
1577,2025-540,Wimbledon,Grass,128,G,2025-06-30,160,200000,25,NaN,...,10,15,28,1825,103,566,2025,atp,singles,main
2831,2025-M-DC-2025-WG1-PO-IND-TOG-01,Davis Cup WG1 PO: IND vs TOG,Hard,4,D,2025-02-01,1,124154,<NA>,NaN,...,<NA>,<NA>,365,135,<NA>,<NA>,2025,atp,singles,main
2719,2025-M-DC-2025-QLS-M-CAN-HUN-01,Davis Cup QLS R1: CAN vs HUN,Hard,4,D,2025-02-01,1,206681,<NA>,NaN,...,<NA>,<NA>,58,960,176,326,2025,atp,singles,main
1830,2025-0421,Canada Masters,Hard,96,M,2025-07-27,365,111575,11,NaN,...,9,11,16,2590,34,1555,2025,atp,singles,main
2942,2025-M-DC-2025-WG2-PO-ZIM-MAR-01,Davis Cup WG2 PO: ZIM vs MAR,Hard,4,D,2025-01-31,2,200611,<NA>,NaN,...,<NA>,<NA>,608,54,<NA>,<NA>,2025,atp,singles,main
2525,2025-0337,Vienna,Hard,32,A,2025-10-20,382,206173,1,NaN,...,6,8,2,10000,16,2430,2025,atp,singles,main
1178,2025-0322,Geneva,Clay,28,A,2025-05-18,369,126239,<NA>,NaN,...,6,9,72,820,46,1146,2025,atp,singles,main

Tournament sample

,official_tournament_id,year,source,source_tournament_id
1671,404,2025,sackmann,2025-0404
1698,5014,2025,sackmann,2025-5014
1700,520,2025,sackmann,2025-520
3357,741,2025,tennis_data_uk,2025_34_eastbourne_eastbourne_international
1657,316,2025,sackmann,2025-0316
1693,747,2025,sackmann,2025-0747
1715,9900,2025,sackmann,2025-9900
3368,422,2025,tennis_data_uk,2025_44_cincinnati_western_southern_financial_...
1684,451,2025,sackmann,2025-0451
1708,7581,2025,sackmann,2025-7581

In [8]:
print("UK sample")
print(df_uk_sample)

print("Sackmann sample")
print(df_sackmann_sample)

print("Tournament sample")
print(df_tournament_sample)

UK sample
              source tour  year  uk_tournament_id  \
889   tennis_data_uk  atp  2025                23
1110  tennis_data_uk  atp  2025                26
1309  tennis_data_uk  atp  2025                29
727   tennis_data_uk  atp  2025                18
1027  tennis_data_uk  atp  2025                25
1472  tennis_data_uk  atp  2025                35
748   tennis_data_uk  atp  2025                18
1264  tennis_data_uk  atp  2025                29
2617  tennis_data_uk  atp  2025                59
1612  tennis_data_uk  atp  2025                36

                  tournament_name   location match_date        series  \
889                Barcelona Open  Barcelona 2025-04-14       atp_500
1110  Internazionali BNL d'Italia       Rome 2025-05-11  masters_1000
1309                  French Open      Paris 2025-06-01    grand_slam
727                    Miami Open      Miami 2025-03-24  masters_1000
1027            Mutua Madrid Open     Madrid 2025-04-29  masters_1000
1472       Mallorca Championships   Mallorca 2025-06-23       atp_250
748                    Miami Open      Miami 2025-03-28  masters_1000
1264                  French Open      Paris 2025-05-28    grand_slam
2617              Open de Moselle       Metz 2025-11-05       atp_250
1612                    Wimbledon     London 2025-07-07    grand_slam

      is_outdoor surface  ... odds_b365_winner  odds_b365_loser  \
889         True    clay  ...             1.44             2.75
1110        True    clay  ...             1.17             5.00
1309        True    clay  ...             1.05            11.00
727         True    hard  ...             1.50             2.63
1027        True    clay  ...             2.00             1.80
1472        True   grass  ...             1.62             2.30
748         True    hard  ...             3.40             1.33
1264        True    clay  ...             2.38             1.57
2617       False    hard  ...             2.75             1.44
1612        True   grass  ...             1.03            13.00

      odds_pinnacle_winner odds_pinnacle_loser odds_max_winner  \
889                   1.46                2.91            1.52
1110                  1.18                5.43            1.20
1309                  1.05               13.88            1.07
727                   1.53                2.69            1.58
1027                  2.06                1.85            2.10
1472                  1.63                2.41            1.68
748                   3.40                1.37            3.40
1264                  2.37                1.66            2.50
2617                  2.77                1.50            2.88
1612                  1.03               18.06            1.05

      odds_max_loser  odds_avg_winner  odds_avg_loser  \
889             2.95             1.45            2.75
1110            5.80             1.17            5.15
1309           14.00             1.04           11.11
727             2.69             1.51            2.54
1027            1.89             2.01            1.82
1472            2.42             1.61            2.29
748             1.37             3.27            1.34
1264            1.66             2.41            1.58
2617            1.45             2.73            1.44
1612           18.06             1.03           13.83

                              source_event_key  \
889           2025_23_barcelona_barcelona_open
1110  2025_26_rome_internazionali_bnl_d_italia
1309                 2025_29_paris_french_open
727                   2025_18_miami_miami_open
1027          2025_25_madrid_mutua_madrid_open
1472   2025_35_mallorca_mallorca_championships
748                   2025_18_miami_miami_open
1264                 2025_29_paris_french_open
2617              2025_59_metz_open_de_moselle
1612                  2025_36_london_wimbledon

                                       source_match_key
889   2025_23_barcelona_barcelona_open_2025-04-14_R3...
1110  2025_26_rome_internazionali_bnl_d_italia_2025-...
1309  2025_29_paris_french_open_2025-06-01_R16_alcar...
727   2025_18_miami_miami_open_2025-03-24_R32_machac...
1027  2025_25_madrid_mutua_madrid_open_2025-04-29_R3...
1472  2025_35_mallorca_mallorca_championships_2025-0...
748   2025_18_miami_miami_open_2025-03-28_SF_mensik_...
1264  2025_29_paris_french_open_2025-05-28_R64_halys...
2617  2025_59_metz_open_de_moselle_2025-11-05_R16_ta...
1612  2025_36_london_wimbledon_2025-07-07_R16_sinner...

[10 rows x 42 columns]
Sackmann sample
                            tourney_id                  tourney_name surface  \
565                          2025-8996                      Santiago    Clay
1220                          2025-520                 Roland Garros    Clay
1677                         2025-0314                        Gstaad    Clay
1577                          2025-540                     Wimbledon   Grass
2831  2025-M-DC-2025-WG1-PO-IND-TOG-01  Davis Cup WG1 PO: IND vs TOG    Hard
2719   2025-M-DC-2025-QLS-M-CAN-HUN-01  Davis Cup QLS R1: CAN vs HUN    Hard
1830                         2025-0421                Canada Masters    Hard
2942  2025-M-DC-2025-WG2-PO-ZIM-MAR-01  Davis Cup WG2 PO: ZIM vs MAR    Hard
2525                         2025-0337                        Vienna    Hard
1178                         2025-0322                        Geneva    Clay

      draw_size tourney_level tourney_date  match_num  winner_id  winner_seed  \
565          28             A   2025-02-24        377     144869            5
1220        128             G   2025-05-26        401     207989            2
1677         28             A   2025-07-14        379     122330            2
1577        128             G   2025-06-30        160     200000           25
2831          4             D   2025-02-01          1     124154         <NA>
2719          4             D   2025-02-01          1     206681         <NA>
1830         96             M   2025-07-27        365     111575           11
2942          4             D   2025-01-31          2     200611         <NA>
2525         32             A   2025-10-20        382     206173            1
1178         28             A   2025-05-18        369     126239         <NA>

     winner_entry  ... l_bpSaved l_bpFaced  winner_rank winner_rank_points  \
565           NaN  ...         4         8           43               1240
1220          NaN  ...         7        14            2               8850
1677          NaN  ...         2         4           34               1585
1577          NaN  ...        10        15           28               1825
2831          NaN  ...      <NA>      <NA>          365                135
2719          NaN  ...      <NA>      <NA>           58                960
1830          NaN  ...         9        11           16               2590
2942          NaN  ...      <NA>      <NA>          608                 54
2525          NaN  ...         6         8            2              10000
1178          NaN  ...         6         9           72                820

      loser_rank  loser_rank_points  source_year tour match_type match_level
565          147                402         2025  atp    singles        main
1220           1              10380         2025  atp    singles        main
1677          74                824         2025  atp    singles        main
1577         103                566         2025  atp    singles        main
2831        <NA>               <NA>         2025  atp    singles        main
2719         176                326         2025  atp    singles        main
1830          34               1555         2025  atp    singles        main
2942        <NA>               <NA>         2025  atp    singles        main
2525          16               2430         2025  atp    singles        main
1178          46               1146         2025  atp    singles        main

[10 rows x 53 columns]
Tournament sample
      official_tournament_id  year          source  \
1671                     404  2025        sackmann
1698                    5014  2025        sackmann
1700                     520  2025        sackmann
3357                     741  2025  tennis_data_uk
1657                     316  2025        sackmann
1693                     747  2025        sackmann
1715                    9900  2025        sackmann
3368                     422  2025  tennis_data_uk
1684                     451  2025        sackmann
1708                    7581  2025        sackmann

                                   source_tournament_id
1671                                          2025-0404
1698                                          2025-5014
1700                                           2025-520
3357        2025_34_eastbourne_eastbourne_international
1657                                          2025-0316
1693                                          2025-0747
1715                                          2025-9900
3368  2025_44_cincinnati_western_southern_financial_...
1684                                          2025-0451
1708                                          2025-7581

## The Process

Yes. I think your tournament mapper lets us improve the GitHub approach substantially.

The linked script starts by joining Tennis-Data and Sackmann on (tour, winner_rank, loser_rank), then uses a fairly broad date window to keep the candidate set manageable. It drops any ambiguous one-to-many candidates, then learns player-name aliases from the accepted links.

Your version can make the first pass much tighter:


```text
Tennis-Data match
        ↓
canonical tournament ID
        ↓
only Sackmann matches in that tournament
        ↓
winner rank + loser rank
        ↓
unique canonical match
        ↓
winner_id / loser_id

```

That should be both faster and safer.

### 1. First enrich both datasets with the same tournament ID

Your tournament mapper is really a bridge table:

```plaintext
year  source          source_tournament_id          official_tournament_id
2025  tennis_data_uk  2025_29_paris_french_open    520
2025  sackmann        2025-520                      520
```

So the first job of the linker should be to attach official_tournament_id to each match dataframe.

I would write a general helper:

In [27]:
import pandas as pd


def attach_tournament_ids(
    matches: pd.DataFrame,
    tournament_mapper: pd.DataFrame,
    *,
    source: str,
    match_tournament_col: str,
) -> pd.DataFrame:
    """Attach canonical tournament IDs to a source's match dataframe.

    If `matches` has no `year` column (e.g. Sackmann's raw match data), it's
    derived from the year prefix embedded in `tourney_id` ("{year}-{number}").
    """
    matches = matches.copy()
    if "year" not in matches.columns:
        matches["year"] = matches["tourney_id"].str.split("-").str[0].astype(int)

    mapper = (
        tournament_mapper.loc[
            tournament_mapper["source"].eq(source),
            [
                "year",
                "source_tournament_id",
                "official_tournament_id",
            ],
        ]
        .drop_duplicates()
    )

    result = matches.merge(
        mapper,
        left_on=["year", match_tournament_col],
        right_on=["year", "source_tournament_id"],
        how="left",
        validate="many_to_one",
    )

    return result.drop(columns="source_tournament_id")

In [28]:
uk = attach_tournament_ids(
    matches=df_uk,
    tournament_mapper=df_tournament,
    source="tennis_data_uk",
    match_tournament_col="source_event_key",
)

sackmann = attach_tournament_ids(
    matches=df_sackmann,
    tournament_mapper=df_tournament,
    source="sackmann",
    match_tournament_col="tourney_id",
)

### 2. Validate tournament coverage immediately

Before touching match linkage:

In [29]:
def tournament_linkage_summary(df: pd.DataFrame) -> pd.Series:
    return pd.Series(
        {
            "matches": len(df),
            "mapped": df["official_tournament_id"].notna().sum(),
            "unmapped": df["official_tournament_id"].isna().sum(),
            "coverage": df["official_tournament_id"].notna().mean(),
        }
    )

In [30]:
print("------UK Check------")
print(tournament_linkage_summary(uk))
print()
print("------Sackmann Check------")
print(tournament_linkage_summary(sackmann))

------UK Check------
matches     2644.0
mapped      2644.0
unmapped       0.0
coverage       1.0
dtype: float64

------Sackmann Check------
matches     2944.000000
mapped      2692.000000
unmapped     252.000000
coverage       0.914402
dtype: float64

### 3. Bootstrap links using exact ranking pairs

Once tournaments are aligned, the first match resolver can be surprisingly simple.

For Tennis-Data:

```plaintext
winner_rank
loser_rank
```

For Sackmann:

```plaintext
winner_rank
loser_rank
```

So candidate generation becomes an indexed dataframe merge:

In [31]:
def generate_rank_candidates(
    uk: pd.DataFrame,
    sackmann: pd.DataFrame,
) -> pd.DataFrame:
    """Generate canonical match candidates using tournament + rank pairs."""

    uk_ranked = uk.dropna(
        subset=[
            "official_tournament_id",
            "winner_rank",
            "loser_rank",
        ]
    ).copy()

    sk_ranked = sackmann.dropna(
        subset=[
            "official_tournament_id",
            "winner_rank",
            "loser_rank",
        ]
    ).copy()

    for df in (uk_ranked, sk_ranked):
        df["winner_rank"] = df["winner_rank"].astype("Int64")
        df["loser_rank"] = df["loser_rank"].astype("Int64")

    candidates = uk_ranked.merge(
        sk_ranked,
        on=[
            "year",
            "tour",
            "official_tournament_id",
            "winner_rank",
            "loser_rank",
        ],
        how="inner",
        suffixes=("_uk", "_sk"),
    )

    return candidates

That's the core of the algorithm.

Notice what we've eliminated.

The GitHub implementation uses:

```text
tour
winner_rank
loser_rank
± date window
```

because it doesn't know that the two rows belong to the same tournament.

We get:

```text
year
tour
official_tournament_id
winner_rank
loser_rank
```

which is substantially stronger.

In [32]:
candidates = generate_rank_candidates(uk, sackmann)
print("------Candidates Check------")
print(tournament_linkage_summary(candidates))

------Candidates Check------
matches     2639.0
mapped      2639.0
unmapped       0.0
coverage       1.0
dtype: float64

### 4. Don't immediately accept every candidate

This part of the original script is especially worth keeping:

ambiguous matches are dropped rather than guessed.

But I would make the ambiguity visible rather than simply discard it.

First give Sackmann a stable match key:

In [33]:
candidates["canonical_match_key"] = (
    candidates["tourney_id"].astype(str)
    + "_"
    + candidates["match_num"].astype(str)
)

In [34]:
def classify_rank_candidates(
    candidates: pd.DataFrame,
) -> pd.DataFrame:
    candidates = candidates.copy()

    candidates["source_candidate_count"] = (
        candidates.groupby("source_match_key")[
            "canonical_match_key"
        ].transform("nunique")
    )

    candidates["canonical_candidate_count"] = (
        candidates.groupby("canonical_match_key")[
            "source_match_key"
        ].transform("nunique")
    )

    candidates["is_unique"] = (
        candidates["source_candidate_count"].eq(1)
        & candidates["canonical_candidate_count"].eq(1)
    )

    return candidates

In [35]:
candidates = classify_rank_candidates(candidates)
print("Ambiguous candidates:", (~candidates["is_unique"]).sum())
print("Unique candidates:", candidates["is_unique"].sum())

Ambiguous candidates: 0
Unique candidates: 2639

Now we can distinguish:

```text
source_match       canonical candidates
----------------------------------------
match_001          1       → accept
match_002          1       → accept
match_003          2       → ambiguous
```

rather than silently throwing information away.

### 5. Round should be supporting evidence

I wouldn't put round in the initial merge key.

Why?

Because you've already done enough tennis-data cleaning to know that source fields can occasionally be imperfect.

Instead:

```text
Tournament       HARD BLOCK
Winner rank      PRIMARY MATCH SIGNAL
Loser rank       PRIMARY MATCH SIGNAL
Round            VALIDATION / DISAMBIGUATION
Names            VALIDATION / FALLBACK
Rank points      VALIDATION / FALLBACK
```

If both datasets have normalized rounds like:

```text
R128
R64
R32
R16
QF
SF
F
RR
```

then after generating candidates:

In [36]:
candidates["round_agrees"] = (
    candidates["round_uk"] == candidates["round_sk"]
)

Most unique rank matches should agree.

If they don't, that's something worth investigating rather than automatically rejecting.

### 6. Rank points are another surprisingly good signal

You have:

UK:
```text
winner_rank
loser_rank
winner_rank_points
loser_rank_points
```

and Sackmann also contains:

```text
winner_rank
loser_rank
winner_rank_points
loser_rank_points
```

So after exact rank matching, we can validate:

In [37]:
candidates["winner_points_diff"] = (
    candidates["winner_rank_points_uk"]
    - candidates["winner_rank_points_sk"]
).abs()

candidates["loser_points_diff"] = (
    candidates["loser_rank_points_uk"]
    - candidates["loser_rank_points_sk"]
).abs()

In [38]:
candidates

,source,tour,year,uk_tournament_id,tournament_name,location,match_date,series,is_outdoor,surface_uk,...,source_year,match_type,match_level,canonical_match_key,source_candidate_count,canonical_candidate_count,is_unique,round_agrees,winner_points_diff,loser_points_diff
0,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-29,atp_250,True,hard,...,2025,singles,main,2025-0339_349,1,1,True,True,0,0
1,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,2025,singles,main,2025-0339_350,1,1,True,True,0,0
2,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,2025,singles,main,2025-0339_355,1,1,True,True,0,0
3,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,2025,singles,main,2025-0339_353,1,1,True,True,0,0
4,tennis_data_uk,atp,2025,1,Brisbane International,Brisbane,2024-12-30,atp_250,True,hard,...,2025,singles,main,2025-0339_351,1,1,True,True,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-14,tour_finals,False,hard,...,2025,singles,main,2025-0605_375,1,1,True,True,0,0
2635,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-14,tour_finals,False,hard,...,2025,singles,main,2025-0605_372,1,1,True,True,0,0
2636,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-15,tour_finals,False,hard,...,2025,singles,main,2025-0605_383,1,1,True,True,0,0
2637,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-15,tour_finals,False,hard,...,2025,singles,main,2025-0605_384,1,1,True,True,0,0
2638,tennis_data_uk,atp,2025,60,Masters Cup,Turin,2025-11-16,tour_finals,False,hard,...,2025,singles,main,2025-0605_385,1,1,True,True,0,0

I wouldn't require equality because the sources could use slightly different ranking snapshots.

But if we see:

```text
rank          exact
rank points   exact/nearly exact
round         exact
tournament    exact
```

that's extraordinarily strong evidence.

### 7. Our first accepted class should be very conservative

I would start with just one match class:

tournament_rank_unique

Requirements:

```text
✓ same year
✓ same tour
✓ same official tournament
✓ same winner rank
✓ same loser rank
✓ exactly one source candidate
✓ exactly one canonical candidate
```

Then generate:

In [39]:
rank_links = candidates.loc[
    candidates["is_unique"]
].copy()

rank_links["match_method"] = "tournament_rank_unique"
rank_links["review_flag"] = False

And keep:

```text
source_match_key
canonical_match_key
official_tournament_id

winner_id
loser_id

winner_rank
loser_rank

round_agrees
winner_points_diff
loser_points_diff

match_method
review_flag
```

This becomes the first piece of your eventual `match_crosswalk`.

### 8. Then measure before adding complexity

This is really important.

**Don't implement name matching yet.**

Run this first and calculate:

In [ ]:
def linkage_summary(
    source: pd.DataFrame,
    links: pd.DataFrame,
) -> pd.Series:
    total = len(source)
    linked = links["source_match_key"].nunique()

    return pd.Series(
        {
            "total_matches": total,
            "linked_matches": linked,
            "unlinked_matches": total - linked,
            "coverage": linked / total,
        }
    )

I want to know:

```text
Total UK matches:           2,???
Tournament mapped:          ??.?%
Exact rank candidates:      ??.?%
Unique rank matches:        ??.?%
Ambiguous rank matches:     ???
No rank candidate:          ???
```

That tells us what problem remains.

We may discover:

```text
92% linked by tournament + rank pair
```

in which case the residual problem is tiny.

Or maybe:

```text
70%
```

because UK and Sackmann use ranking snapshots differently.

Then we design Pass 2 based on the **actual residuals**.

### 9. Where the GitHub name-map idea comes next

This is the part I absolutely would borrow from the reference implementation.

It learns:

```text
Tennis-Data name
        ↓
Sackmann player ID
```


only from matches that have already been independently linked by rankings. It requires repeated observations and 90% agreement before trusting the alias.

That's clever because we're not saying:

```text
"Sinner J." looks like "Jannik Sinner"

```

We're saying:

```text
Across 47 matches independently identified through
tournament + ranks:

"Sinner J." corresponded to player 206173
47 / 47 times.

```

That is a much stronger entity-resolution mechanism.

And ours is even safer because our seed matches have already been tournament-blocked.

### 10. The algorithm I see emerging

I'd structure the eventual resolver as:

```text
PASS 0 — Tournament resolution
─────────────────────────────
UK source_event_key
         ↓
official_tournament_id
         ↑
Sackmann tourney_id


PASS 1 — Exact rank linkage
───────────────────────────
official tournament
+ winner rank
+ loser rank
         ↓
unique 1:1 match


PASS 2 — Learn player aliases
─────────────────────────────
trusted Pass-1 matches
         ↓
UK name → canonical player ID
         ↓
require repeated dominant mapping


PASS 3 — Player-pair linkage
────────────────────────────
official tournament
+ winner player ID
+ loser player ID
         ↓
unique canonical match


PASS 4 — Residual scoring
─────────────────────────
tournament
+ rank proximity
+ player-name compatibility
+ round
+ rank points
+ opponent identity
         ↓
high confidence / review / unmatched
```

And importantly:


```text
Never fuzzy match the entire annual dataset.
```

Everything after Pass 0 happens inside one canonical tournament.

#### What I would implement right now

Only these three functions:

```python
attach_tournament_ids()
generate_rank_candidates()
classify_rank_candidates()
```

Then run them against 2025 and inspect the metrics.

I would **not implement the player-name mapper yet**. The next useful thing to learn is exactly how much coverage `official_tournament_id` + `winner_rank` + `loser_rank` gives you.

That empirical result should determine Pass 2 rather than us prematurely designing a complicated matcher.