In [9]:
import ssl
import urllib.request

import truststore

# use macOS Keychain (needed behind corporate TLS-inspecting proxies like Zscaler);
# also force a fresh opener since the kernel may have already built one with the old context
truststore.inject_into_ssl()
urllib.request.install_opener(
    urllib.request.build_opener(urllib.request.HTTPSHandler(context=truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)))
)

import pandas as pd

In [10]:
df = pd.read_csv("https://stats.tennismylife.org/data/2026.csv")

df

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2026-9900,United Cup,Hard,18,A,O,20260102,1,B0BI,NaN,...,6.0,7.0,0.0,52.0,39.0,25.0,6.0,10.0,2.0,6.0
1,2026-9900,United Cup,Hard,18,A,O,20260102,2,TE51,NaN,...,2.0,1.0,3.0,57.0,30.0,22.0,11.0,9.0,5.0,8.0
2,2026-9900,United Cup,Hard,18,A,O,20260103,3,Z371,NaN,...,0.0,18.0,5.0,126.0,75.0,58.0,29.0,18.0,9.0,10.0
3,2026-9900,United Cup,Hard,18,A,O,20260103,4,W367,NaN,...,4.0,17.0,5.0,111.0,61.0,50.0,32.0,18.0,6.0,7.0
4,2026-9900,United Cup,Hard,18,A,O,20260103,5,B0BI,NaN,...,11.0,23.0,2.0,102.0,56.0,43.0,21.0,16.0,4.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,2026-6242,Winston-Salem,Hard,48,M,O,20260828,43,F0DM,4.0,...,1.0,8.0,7.0,88.0,49.0,38.0,20.0,15.0,3.0,5.0
2128,2026-6242,Winston-Salem,Hard,48,M,O,20260828,44,D994,NaN,...,8.0,1.0,6.0,105.0,51.0,30.0,31.0,15.0,6.0,12.0
2129,2026-6242,Winston-Salem,Hard,48,M,O,20260829,45,B0ID,3.0,...,6.0,4.0,4.0,88.0,56.0,35.0,10.0,13.0,7.0,13.0
2130,2026-6242,Winston-Salem,Hard,48,M,O,20260829,46,F0DM,4.0,...,0.0,0.0,4.0,47.0,29.0,22.0,7.0,7.0,3.0,4.0
2131,2026-6242,Winston-Salem,Hard,48,M,O,20260830,47,B0ID,3.0,...,1.0,0.0,1.0,39.0,28.0,13.0,6.0,8.0,3.0,7.0

In [2]:
import pandas as pd

df = pd.read_csv("https://stats.tennismylife.org/data/2026.csv")
df.head()

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)>

In [3]:
from io import BytesIO

import pandas as pd
import requests


url = "https://stats.tennismylife.org/data/2026.csv"

response = requests.get(url, timeout=30)
response.raise_for_status()

df = pd.read_csv(BytesIO(response.content))

df.head()

SSLError: HTTPSConnectionPool(host='stats.tennismylife.org', port=443): Max retries exceeded with url: /data/2026.csv (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1010)')))

In [1]:
import truststore

truststore.inject_into_ssl()

import pandas as pd
import requests

In [2]:
url = "https://stats.tennismylife.org/data/2026.csv"

response = requests.get(url, timeout=30)
response.raise_for_status()

print(response.status_code)

200

In [4]:
df = pd.read_csv(url)
df

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2026-9900,United Cup,Hard,18,A,O,20260102,1,B0BI,NaN,...,6.0,7.0,0.0,52.0,39.0,25.0,6.0,10.0,2.0,6.0
1,2026-9900,United Cup,Hard,18,A,O,20260102,2,TE51,NaN,...,2.0,1.0,3.0,57.0,30.0,22.0,11.0,9.0,5.0,8.0
2,2026-9900,United Cup,Hard,18,A,O,20260103,3,Z371,NaN,...,0.0,18.0,5.0,126.0,75.0,58.0,29.0,18.0,9.0,10.0
3,2026-9900,United Cup,Hard,18,A,O,20260103,4,W367,NaN,...,4.0,17.0,5.0,111.0,61.0,50.0,32.0,18.0,6.0,7.0
4,2026-9900,United Cup,Hard,18,A,O,20260103,5,B0BI,NaN,...,11.0,23.0,2.0,102.0,56.0,43.0,21.0,16.0,4.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2127,2026-6242,Winston-Salem,Hard,48,M,O,20260828,43,F0DM,4.0,...,1.0,8.0,7.0,88.0,49.0,38.0,20.0,15.0,3.0,5.0
2128,2026-6242,Winston-Salem,Hard,48,M,O,20260828,44,D994,NaN,...,8.0,1.0,6.0,105.0,51.0,30.0,31.0,15.0,6.0,12.0
2129,2026-6242,Winston-Salem,Hard,48,M,O,20260829,45,B0ID,3.0,...,6.0,4.0,4.0,88.0,56.0,35.0,10.0,13.0,7.0,13.0
2130,2026-6242,Winston-Salem,Hard,48,M,O,20260829,46,F0DM,4.0,...,0.0,0.0,4.0,47.0,29.0,22.0,7.0,7.0,3.0,4.0
2131,2026-6242,Winston-Salem,Hard,48,M,O,20260830,47,B0ID,3.0,...,1.0,0.0,1.0,39.0,28.0,13.0,6.0,8.0,3.0,7.0